name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  main-deploy:
    if: github.ref == refs/heads/main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install, lint, build 🔧
        run: |
          npm install
          npm run lint:js
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages-main
          folder: build
  dev-deploy:
    main-deploy:
      if: github.ref == refs/heads/dev
      runs-on: ubuntu-latest
      steps:
        - name: Checkout 🛎️
          uses: actions/checkout@v2.3.1

        - name: Install, lint, build 🔧
          run: |
            npm install
            npm run lint:js
            npm run build

        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@4.1.0
          with:
            branch: gh-pages-dev
            folder: build
